### ISSUE TITLE
demo wiki

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#1]
Why not using github pages and add a demo wiki?

**Comment by flibbles** [comment]
I probably will do that. I made myself release today so I wouldn't keep putting it off. I'm still polishing a few edges.

**Comment by kookma** [comment]
@flibbles thank you!
Yes, many people are not familiar with node.js when you have a demo, it will be easy to drag and drop the plugin from it to other wikis.

Any way this is a great addition to TW.

**Comment by sycom** [comment]
I know you can do that here using Travis-CI, but making a mirror on a gitlab instance, will allow you to automatically _build / deploy_ on _.io page_ via a `gitlab-ci.yml` file.

See my TiddlyWiki-Plugins project repo to see an example...

**Comment by flibbles** [comment]
@sycom, thank youfor the suggestion. I looked into gitlab, and if this were a bigger project, that would definitely be the way to go. But for one this small, I've decided to go with github pages.

That said: [Here it the new demo site!](https://flibbles.github.io/tw5-relink/)

Let me know what you think!
