### ISSUE TITLE
Relink doesn’t work with markdown-wikitext hybrid

### ISSUE THREAD

**Issue by avks** [flibbles/tw5-relink#18]
Hello, 

First of all, thank you for this plugin. I can change titles without worries. But I am currently using a hybrid of Markdown and wikitext. To parse wikitext’s `[[Title of Tiddler]]` into links inside markdown tiddlers, I am using this:
```
\rules only html image macrocallinline syslink transcludeinline wikilink filteredtranscludeblock macrocallblock transcludeblock prettylink
```
…inside `$:/config/markdown/renderWikiTextPragma` (thanks to David Gifford’s [Stroll](https://giffmex.org/stroll/stroll.html)).

I guess Relink parses tiddlers based on `type`. Since my tiddlers _are_ markdown and wikiLinks are inside them, Relink doesn’t change the links if I change titles. Is there any way I can make it work?

**Comment by flibbles** [comment]
It should be working. Relink respects `$:/config/markdown/renderWikiTextPragma`. Can you send me the body of the tiddler where the link exists?

**Comment by avks** [comment]
Yes, the idiot in me didn’t install Relink-markdown. Read it here: https://github.com/flibbles/tw5-relink/issues/12#issuecomment-633766668.

Installed relink for markdown and it works perfectly.

Thanks again for this plugin!

**Comment by flibbles** [comment]
No problem! Just glad it's working for you.
