### ISSUE TITLE
The plugin doesn't contain a Lizense tab 

### ISSUE THREAD

**Issue by pmario** [flibbles/tw5-relink#19]
Hi the plugin should contain a lizense tab like eg: https://wikilabs.github.io/editions/uni-link/#%24%3A%2Fplugins%2Fwikilabs%2Funi-link or something similar. ... 

So it's not necessary to include the whole text. Just add a mini-tiddler with your copyright and a link to your homepage lizense or to the lizense template as I did.

**Comment by flibbles** [comment]
I'll slip this in with the next release.

**Comment by flibbles** [comment]
Took me a while. Didn't want to make a full release just for the license, but it's done now.
