### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#2]
The configuration tab is not clear and needs explanation and example.

I did some test, list, tag and simple link like [[TidA]] work fine! but filter does not work like

```
<$list filter="[tag[TidA]]">
....
</$list>
```

**Comment by flibbles** [comment]
You're right. I'll see about adding some descriptor text to those configuration files, and maybe show an example for what kind of substitution each configuration would enable.

**Comment by flibbles** [comment]
(So I'm not making this in a complete vacuum, I'm putting the explanation and examples here first)

Fields and attributes are whitelisted individually. So if we take:
![Screen Shot 2019-08-22 at 10 56 37 AM](https://user-images.githubusercontent.com/205465/63525369-96dd4700-c4cb-11e9-9588-541d640415ff.png)
There are three custom fields.

* _subpages_ is a filter. Which means if a tiddler has a field called _subpages_ any value it has will be interpreted as a filter, so  `[tag[tidA]!has[draft.of]` should become `[tag[tidB]!has[draft.of]]`
* _examples_ is a list. So any _examples_ fields of all tiddlers will be treated as a list string. So `tidA [[Another tiddler]]` will become `tidB [[Another tiddler]]`
* _test_ is a title. Simplest. `tidA` becomes `tidB`, but `tidA anotherTiddler` doesn't become `tidB anotherTiddler`

All this is the same for attribute values. Where you specify an element, and an attribute, and it's type.
![Screen Shot 2019-08-22 at 11 02 35 AM](https://user-images.githubusercontent.com/205465/63525855-634eec80-c4cc-11e9-8d7f-92cdc87e59cf.png)

You may notice I changed the _field_ option to _title_, which I think is more descriptive. But I'm also thinking _tiddler_ may have been better. I'm not sure.

Anyway, does this make sense to you? I'll be adding this sort of description to the configuration pages soon.

**Comment by kookma** [comment]
@flibbles 
Good move! Yes things are more understandable now.

**Comment by flibbles** [comment]
This is now a [demo site](https://flibbles.github.io/tw5-relink/) which contains more thorough documentation, as well as a neat little demo.

The configuration pages all link to the corresponding documentation pages, and the documentation will probably polish up over time.

**Comment by kookma** [comment]
Thanks @flibbles 
I recommend to announce it in Google Forum!
