### ISSUE TITLE
Rename backlinks inside a macrocall

### ISSUE THREAD

**Issue by kebifurai** [flibbles/tw5-relink#21]
I'm using this plugin https://sobjornstad.github.io/TiddlyRemember
To create cards that sync with an external program, so in TiddlyWiki I have to write text and also backlinks inside macrocalls.

Something like this:
<$macrocall $name="myMacro" text="this is some content with a [[backlink]]"/>

But I noticed that relink doesn't update backlnks when inside a macrocall.
Is this a bug or is it normal behavior??

**Comment by flibbles** [comment]
Do you have your macro whitelisted? The best way to do it (assuming this is a user-defined macro) is to use the relink pragma:
```
\relink myMacro text wikitext
\define myMacro(text) ...
```

**Comment by kebifurai** [comment]
Sorry, didn't realize I haven't setup the whitelist, now it works.
Thank you for your fast reply.
