### ISSUE TITLE
Dealing with prefixed titles

### ISSUE THREAD

**Issue by AnthonyMuscio** [flibbles/tw5-relink#22]
Hi,

I was just building a solution on tiddlywiki which involves having a form of shadow tiddler, I call a ghost tiddler which is a prefix of the target tiddler. In fact there are already examples like this in the core tiddlers 
eg $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/close-all
Basically there exists a tiddler of the form prefix $:/config/PageControlButtons/Visibility/ for the tiddler $:/core/ui/Buttons/close-all

There are also operators such as the lookup operator, designed to make use of this and the prefix/suffix handling. 

I was wondering if it is possible to configure the relink plugin, or a possible update, that would allow the rename of a tiddler to also operate on any named prefixes. For example

MyTiddler may have a tiddler called $:/namespace/MyTiddler
Can we get the renaming of MyTiddler to update the title of $:/namespace/MyTiddler
For Example MyTiddler becomes "Renamed Tiddler" and $:/namespace/MyTiddler becomes $:/namespace/Renamed Tiddler

My Thought is perhaps relink needs the namespace to be given eg  $:/namespace/ and only then each time a tiddler is renamed the tiddlers with that or other name spaces configured get the suffix renamed.

This would allow any prefix based solution to be more robust and in the case of additional config tiddlers the configuration will move with a tiddler on rename.

I love this plugin and believe its only a matter of time in it will be in the core plugins.

Thanks
Tony/TW Tones

**Comment by flibbles** [comment]
Interesting.

It's outside the scope of Relink, but it wouldn't be for a Relink plugin. I'll look into it.

**Comment by flibbles** [comment]
Also, I assume you meant that ghost tiddlers are *system* tiddlers, since it doesn't make sense for shadow tiddlers, and also Relink doesn't touch shadow tiddlers by default.

**Comment by flibbles** [comment]
I've been looking into how to make a sub-plugin out of this, and I got hit with analysis paralysis. This is what I have so far:

```javascript
/*\
module-type: relinkoperator
title: $:/plugins/flibbles/relink/js/relinkoperations/ghosts.js
type: application/javascript

Renames ghost tiddlers of the relinked tiddler. In this case, ones that have the title `$:/prefix/` + title.

\*/

/*jslint node: false, browser: true */
/*global $tw: false */
"use strict";

var prefix = "$:/prefix/";

var EntryNode = require('$:/plugins/flibbles/relink/js/utils/entry');

var GhostEntry = EntryNode.newType("ghost");

GhostEntry.prototype.report = function() {
    return ["title: " + prefix + "..."];
};

exports['ghosts'] = function(tiddler, fromTitle, toTitle, changes, options) {
    if (tiddler.fields.title === prefix + fromTitle) {
        var entry = new GhostEntry();
        entry.output = prefix + toTitle;
        changes.title = entry;
    }
};
```

It renames all tiddlers that have the name `$:/prefix/MyTidder`. (Note: You need to have Relink 1.10.1 which I just released for this to work correctly)

I'd like there to be a more all-purpose subplugin from this. Maybe something where you can specify multiple prefixes on a configuration page, or suffixes. And maybe have some way for other plugins to introduce their own namespacing schemes. I was thinking through filters or something, sort of like how `$:/config/FileSystemPaths` works, but I can't decide on a good way.

I'm giving what I have to you. I'd welcome your input, or if you think this solution is good enough for you.

**Comment by flibbles** [comment]
I'm going to close this since it seems to be a stale thread. Feel free to open it if this is still a concern for you.

**Comment by flibbles** [comment]
@AnthonyMuscio, I don't know if you still care, but I have built a supplemental plugin which addresses the renaming of tiddlers related to the target tiddler. I discuss it more in issue #25. I'd love to know if this suits your needs.

I mention it briefly in the other issue, but one concern I have with the current implementation is that there isn't a way to register filters with a 3rd party plugin such that they'll automatically take effect. You can get a _checkbox_ custom to your plugin which appears in the Relink-titles configuration, but the user currently would need to check that box, since it modifies one conglomerated filter.

**Comment by flibbles** [comment]
I'm fairly sure you died in a tragic car accident months ago, but I thought you should know that the new _Relink-titles_ supplemental plugin addresses your problem fully.
