### ISSUE TITLE
Treat all *.ref fields as title and *.refs fields as list and update them accordingly?

### ISSUE THREAD

**Issue by rimi** [flibbles/tw5-relink#26]
Hi,

in my wiki i have a this startup-hook: https://github.com/rimi/tw5-rimir-common/blob/main/extensions/core/hooks/relink-refs-on-rename.js
It is intended to update titles inside every field that ends with ".ref" (type:title) and ".refs" (type:list) on title-changes (i use this consistently across all my wiki-data). 

As i understand your project so far, one is only able to specify fields explicitly by name. Actually i would like to retire my script in favor of your plugin, because i like all the other features you provide ;). 

Would it be possible for you to enhance the field-configuration to put in there a regexp-type stating e.g. "*.ref"?

Thanks in advance,
Mirko

**Comment by flibbles** [comment]
So that's a little outside the scope of Relink to do that, but Relink is designed to be extensible. If you plug the following module into your project, then Relink will do exactly as you describe.
``` javascript
/*\
module-type: relinkoperator
title: myRelinkRefsModule
type: application/javascript

Handles all fields with ".ref" and ".refs" suffixes.

\*/

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

var settings = require('$:/plugins/flibbles/relink/js/settings.js');
var EntryNode = require('$:/plugins/flibbles/relink/js/utils/entry');

var FieldEntry = EntryNode.newType("refField");

FieldEntry.prototype.report = function() {
	return [this.field];
};

exports['refFields'] = function(tiddler, fromTitle, toTitle, changes, options) {
	$tw.utils.each(tiddler.fields, function(value, field) {
		var handler
		if (field.endsWith(".ref")) {
			handler = settings.getType("title");
		} else if (field.endsWith(".refs")) {
			handler = settings.getType("list");
		}
		if (handler) {
			var entry = handler.relink(value, fromTitle, toTitle, options);
			if (entry) {
				var fieldEntry = new FieldEntry();
				// Setting field allows this entry to report properly in //Relink// references tab.
				fieldEntry.field = field;
				// Setting output allows the change to bubble up if this entry is somehow nested.
				fieldEntry.output = entry.output;
				// Needed, in case the relink was impossible. This allows it to report that.
				fieldEntry.add(entry);
				changes[field] = fieldEntry;
			}
		}
	});
};
```
Let me know if this works for you.

-Flibbles

**Comment by rimi** [comment]
Hi!

thanks, works like a charm! (https://github.com/rimi/tw5-rimir-common/blob/main/extensions/relink/relinkoperators/relink-refs-on-rename.js)

Mirko

**Comment by flibbles** [comment]
Glad I could help!

Though I do recommend you double check the meta file on that module you just linked. It's got the fields "with", "special", "thanks", "to", and "flibbles".

**Comment by rimi** [comment]
Whoops... wasn't aware that TW5 parses the stuff after "/*\" even if the tiddler is defined as "application/javascript"WITH a .meta file. I thought that would only be taken into account if i have a JS-File WITHOUT .meta in the FS...

Anyway, thanks for that hint!

--mirko

Mirko

**Comment by rimi** [comment]
I tried to reproduce that behavior but i couldn't. Not sure what happened... ;)

--mirko

**Comment by flibbles** [comment]
I just pulled your file and tested it. And it renamed .ref and .refs fields.

But reading your comment again, it looks like you're talking about the extraneous fields glitch. Gust glad everything is working out.

**Comment by rimi** [comment]
yes, everything fine (y)

**Comment by flibbles** [comment]
Dear sir or ma'am,

I don't know if you're still listening to this thread, but Relink V2 has just been released. It overhauls the way several internal mechanisms work. And unfortunately some of the modules needed to change.

The current module I wrote you will continue to relink just as you'd expect, but if you upgrade, and you'd like the Relink TiddlerInfo panel to work, just replace your module with this:
```javascript
/*\
module-type: relinkoperator
title: myRelinkRefsModule
type: application/javascript

Handles all fields with ".ref" and ".refs" suffixes.

\*/

/*jslint node: true, browser: true */
/*global $tw: false */
"use strict";

var settings = require('$:/plugins/flibbles/relink/js/settings.js');

exports.name = 'refFields';

exports.report = function(tiddler, callback, options) {
	$tw.utils.each(tiddler.fields, function(value, field) {
		var handler;
		if (field.endsWith(".ref")) {
			handler = settings.getType("title");
		} else if (field.endsWith(".refs")) {
			handler = settings.getType("list");
		}
		if (handler) {
			handler.report(value, function(title, blurb) {
				callback(title, field);
			}, options);
		}
	});
};

exports.relink = function(tiddler, fromTitle, toTitle, changes, options) {
	$tw.utils.each(tiddler.fields, function(value, field) {
		var handler
		if (field.endsWith(".ref")) {
			handler = settings.getType("title");
		} else if (field.endsWith(".refs")) {
			handler = settings.getType("list");
		}
		if (handler) {
			var entry = handler.relink(value, fromTitle, toTitle, options);
			if (entry) {
				changes[field] = entry;
			}
		}
	});
};
```

Let me know if you have any questions.
