### ISSUE TITLE
Update field names if they match an existing title

### ISSUE THREAD

**Issue by grooveboxunited** [flibbles/tw5-relink#29]
The next version of TiddlyWiki (v5.2.0) will remove character restrictions for field titles. This will make it much more reasonable to have tiddlers that represent fields. For example I might have a field named "Author", and a matching tiddler called "Author" in which I can note details about how I use the field.

It would be very useful if Relink had an option to rename fields if they correspond to a tiddler in this way.

Thanks for the great plugin.

**Comment by flibbles** [comment]
wuuut?

Didn't Tiddlywiki already have something like this. A tiddler named `$:/language/Docs/Fields/Author` would already contain description information about the Author field.

I know nothing about this new feature, but doesn't it seem dangerous to change the field keys like that? I guess I'll need to read up on this.

**Comment by flibbles** [comment]
I can't find a PR or issue that corresponds to this feature you're describing. Do you have a number for it?

**Comment by grooveboxunited** [comment]
I don't know much about the technicals but I think this change is main reason for the jump from 5.1 to 5.2. Here's the thread where Jeremy announced the pre-release: https://groups.google.com/g/tiddlywiki/c/kF-OGmkyFfo

That thread links to the [PR](https://github.com/Jermolene/TiddlyWiki5/pull/5708) and the [documentation for the new format](https://tiddlywiki.com/prerelease/dev/#Data%20Storage%20in%20Single%20File%20TiddlyWiki).

There's a bit more explanation here: https://groups.google.com/g/tiddlywiki/c/eccIEHZoxsI/m/_MWs3EooBAAJ

> Didn't Tiddlywiki already have something like this. A tiddler named $:/language/Docs/Fields/Author would already contain description information about the Author field.

Yeah that's how you can add a description, but I'm talking about something a bit more general. I'm suggesting that it will soon be more common for users to think of field names (as opposed to just field values, links and tags) as representing tiddlers, and so it might make sense for them to be seen as such by Relink.

**Comment by flibbles** [comment]
Oh, so there wouldn't actually be an explicit thing where Tiddlywiki ties field names with tiddlers? It's just a relationship that end-users might interpret for themselves?

If that's so, then this follows outside the scope of core Relink, since they aren't technically links or references in any way except in the end-user's head.

But it wouldn't be hard to write a simple module that could do what you describe.

**Comment by grooveboxunited** [comment]
> Oh, so there wouldn't actually be an explicit thing where Tiddlywiki ties field names with tiddlers? It's just a relationship that end-users might interpret for themselves?

Yes as far as I know that's right, sorry if I was not being clear.

> But it wouldn't be hard to write a simple module that could do what you describe.

Would this be a Relink plugin or a standalone thing? It might make a good first project for when I finally get around to learning how to create javascript plugins.

**Comment by grooveboxunited** [comment]
test

**Comment by grooveboxunited** [comment]
Wow thank you @flibbles, I will try this out in the coming weeks.

**Comment by flibbles** [comment]
If you yet still interested, I've just published a supplemental plugin called [relink-fieldnames](https://flibbles.github.io/tw5-relink/). It does what that module I gave you does, only better and more robustly, and it's amply tested.

**Comment by flibbles** [comment]
And if you're interested still, relink-fieldnames has been greatly enhanced, so not only does it update the fields now, it can also update all occurrences where that field may be referenced, such as `{{tiddler!!myField}}`. That plugin is now a comprehensive plugin for renaming fields.
