### ISSUE TITLE
How to download/install for single html file TW

### ISSUE THREAD

**Issue by hchaase** [flibbles/tw5-relink#3]
can you please add a description of how to install on single file TW version? I assume I can use the package.json file, but I am just guessing. 

If this works as you describe, it is an incredible addition to tw.. I would say core material..

**Comment by flibbles** [comment]
Hopefully I'll have a single file download available either by today or tomorrow.

**Comment by flibbles** [comment]
Okay, it took me a few days (and there's a lot of work to do yet), but I've done it.

There are now instructions for how to install on a single file TW on the [new demo site](https://flibbles.github.io/tw5-relink/). Let me know if you have any trouble!

**Comment by hchaase** [comment]
thaks

very through and good examples. !!!
This fix a long standing shortcoming of TW
