### ISSUE TITLE
Distributing Relink via a third party plugin

### ISSUE THREAD

**Issue by saqimtiaz** [flibbles/tw5-relink#30]
I would like to request permission to distribute the relink plugins via my plugin library that I am setting up at https://saqimtiaz.github.io/SQPL/

The motivations behind the request are:

- To be able to specify Relink as a dependency with the Streams plugin, so that installing Streams from the library automatically installs Relink as well
- Testing out a plugin updates notification mechanism. This plugin library is in part meant to inform the process of creating an official community plugin library that plugin authors can choose to have their plugins included in.

The plugin library in question is automatically re-generated every 60 minutes from the latest git tag for a plugin, so it would automatically keep up to date with Relink releases. 

Thank you.

**Comment by flibbles** [comment]
Sure. I think all that's required is the retention of the license, which will happen automatically if you import Relink as-is.

By the way, I'm noticing that Streams is using Relink-Titles's built-in "Rename subdirectories" rule for managing streams, which works, but it does flood the //Relink// references panel will all those `${tiddler title}/202012...` stream tiddlers. Also, if someone were to want to disable relink-title's default behavior, they couldn't do so without shutting off proper stream relinking either.

Relink-Titles is designed to (and intended to) support custom rules, and it might be worth having one for Streams. Although I recognize that you'd have to override the "Rename subdirectories" rule to first make it ignore your streams.

**Comment by saqimtiaz** [comment]
> Sure. I think all that's required is the retention of the license, which will happen automatically if you import Relink as-is.

Thank you and yes, the plugin will be distributed completely unchanged.

> Relink-Titles is designed to (and intended to) support custom rules, and it might be worth having one for Streams. Although I recognize that you'd have to override the "Rename subdirectories" rule to first make it ignore your streams.

I will have a look at this, thank you. Relink-Titles was released after Streams was available and I'll admit I haven't looked at it properly apart from recognizing that it would be helpful to users of Streams.
