### ISSUE TITLE
Dragging the link to install the plugin does not install the plugin

### ISSUE THREAD

**Issue by deshmukhs** [flibbles/tw5-relink#31]
Running TiddlyDesktop version 0.0.15-prerelease.2 and empty.html from the tw website.

When I drag the installation tablet to my wiki, an Untitled tiddler gets imported, not $:/plugins/flibbles/relink.

$:/plugins/flibbles/relink tiddler is shown missing.

There is no trace of plugin in the plugin area.

Is there a way I can install the plugin in the given setup?

**Comment by flibbles** [comment]
This sounds more like a problem with TiddlyDesktop than with Relink. Are you able to import other tiddlers and plugins?

You might try...

1. Click on the tablet instead.
2. When the Relink plugin opens, go to that tiddler's extended options and select export tiddler
3. Do so as a ".tid file"
4. In tiddly desktop, click the tools tab on the right
5. Click "Import", and then navigate and select the downloaded "$ _plugins_flibbles_relink.tid" file

**Comment by deshmukhs** [comment]
This could have been due to TiddlyDesktop.

I did as you suggested and things work as expected.

Thanks!
