### ISSUE TITLE
Is it possible to do the relink inside table?

### ISSUE THREAD

**Issue by hkw1831** [flibbles/tw5-relink#32]
Hello I am using your plugin frequently and I would wonder can the tiddler be relinked inside the table :bow:

When I go to the tiddler "Demo/Transcludes" on interactive page https://flibbles.github.io/tw5-relink/ and added a table there:

```
[[With template|Templates/Hello]]:
{{Frodo||Templates/Hello}}

Weapon of choice: {{Frodo!!weapon}}

Adding a table here:

|{{Frodo||Templates/Hello}}|

{{Frodo}}

```

After that, when I try to rename Frodo to a new name, the Frodo with the transclusion template inside the table does not relink to the new name.

Is there any chance to relink this case?

Thank you very much,

Regards,

Wing

**Comment by flibbles** [comment]
Ooh poops. I completely forgot about tables. This is less of a glitch, and more of an entire rule I forgot to include.

This'll take me a day or two.

**Comment by hkw1831** [comment]
Thank you very much :D

**Comment by flibbles** [comment]
As of V2.0.2 released today, this problem is fixed.
