### ISSUE TITLE
[Bug] Relink Does Not Refresh Report When you Clear Title

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#35]
To reproduce the bug

1. open https://flibbles.github.io/tw5-relink/
2. create a base tiddler
3. create some tiddlers with relation (tag with base tiddler or link to base tiddler)
4. no open base tiddler and try rename it
5. relink reports the affected tiddler
6. clear the title
7. report disappear
8. enter new name reports is not the report!

![img_643_%pn](https://user-images.githubusercontent.com/830394/140657243-26af651e-7c79-4b1d-9452-f46236e94c34.gif)

NOTE: If you clear the title completely then Relink does not show the report!

**Comment by kookma** [comment]
More input:
- if you clear the title, relink does not show the report nor does the relinking
- if you uncheck/check the `Use Relink to update ... to ... across all other tiddlers`  it will refreshes report and work again

**Comment by flibbles** [comment]
I hope this isn't crucial. I just finished my next Uglify release and I could use a few days, but I will get to this. Thank you for pointing it out.

**Comment by flibbles** [comment]
Fixed as of v2.1.2
