### ISSUE TITLE
[Idea] Rename on Title Everywhere in the Path

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#36]
Relink title does a great job on `from/path/ptah...` to `to/path/path`

Does it make sense, if Relink title intrinsically supports the below criteria:

1. `path/path/from-oldtid`  to `path/path/to-newtid`
2. `path/from-oldtid/path` to `path/to-newtid/path`

That means a tiddler title in a path is distinguishable by delimiter `/` a word or a compound words is interpreted as a tiddler title if and only if it appears in another tiddler title delimited by `/`. So if a parent tiddler is `mytid` then another tiddler with `$:/temp/first/mytid` is a subtiddler of `mytid` and also `$:/temp/mytid/second`

So, no matter to start from `title/path/...`  or end by `path/.../title`.

I just worry to break the definition of subtiddler, as a subtiddler has a title like `parent/path` not `path/parent`! Please ignore this OP if you think, it causes confusion!

**Comment by flibbles** [comment]
I just released a new version of Relink-titles which should allow anyone to write simple one-line patterns describing rename rules that should cover all of these cases if they should want, but I don't think it should do this by default. It would have too many unintended side-effects.
