### ISSUE TITLE
Links to external docs in the plugin configuration text don't respect palette colors

### ISSUE THREAD

**Issue by Natronium** [flibbles/tw5-relink#37]
with a dark palette selected the default anchor dark blue and dark purple are basically unreadable thanks to the (lack of) contrast:
![badtext2](https://user-images.githubusercontent.com/25114018/147603769-c697fe63-5090-4417-9e07-8c1a05665e0b.png)
![badtext](https://user-images.githubusercontent.com/25114018/147603811-5a2e0f9f-29e9-484a-bd66-10e5f3be9ef2.png)

since it looks like you're doing [transcludular](https://github.com/flibbles/tw5-relink/blob/88edc8b3febc7a9bfc27181b06ab5e86c8bf6d9c/docs/library/recipes/library/tiddlers.json#L15) [stuff](https://github.com/flibbles/tw5-relink/blob/913ceb471d4dcad5c409621f4e4d268bbc13f4db/plugins/relink/tiddlers/language.multids#L22) that probably prevents you using double square brace links, but i think you can still solve the issue by adding the `tc-tiddlylink-external` class to your anchors, since that's what seems to be in use by behaving external links. it seems possible that the `<$link>` widget might do the right thing, but i've'nt the experience to make a claim either way.

**Comment by flibbles** [comment]
Yeah, the <$link> widget is more appropriate (and would adjust its theme correctly). I only recently learned about how to make those widgets link to external links. I'll change this out with the next release.

**Comment by flibbles** [comment]
Relink is now more adaptive to the current palette.
