### ISSUE TITLE
[minor] fix text when renaming tiddler

### ISSUE THREAD

**Issue by hchaase** [flibbles/tw5-relink#4]
when you rename a tiddler you get teh warning

" The following references to this tiddler will not be automatically updated:"

but with this plugin it will, so maybe change this text to somthing like

" The following references to this tiddler will be automatically updated:"

**Comment by flibbles** [comment]
Oh wow. Yeah. That notification was added back in Novembers, and somehow I've gone nearly eight months without noticing it. It'll be addressed in the next release.

Thanks for pointing it out.
