### ISSUE TITLE
tiny typo in "Relink" on the Demo Site

### ISSUE THREAD

**Issue by zhurnaly** [flibbles/tw5-relink#44]
in https://flibbles.github.io/tw5-relink/ the word "propagating" is misspelled _(in the sentence "This is the demo site for Relink, the Tiddlywiki5 plugin which aids in renaming tiddlers by propogating the change across all existing tiddlers.")_ 

😉  and **THANK YOU** for _Relink_!

**Comment by flibbles** [comment]
Fixed. Thank you!
