### ISSUE TITLE
Relink fails to rename referred links in tiddlers with markdown format

### ISSUE THREAD

**Issue by Darleey** [flibbles/tw5-relink#45]
Tiddlywiki Version： 5.2.7

By the way, in earlier versions, Relink would convert Chinese character into basic code while it is executed in tiddlers with markdown format. 
For example `[](#文字)` would be converted ioto `[](#%E6%96%87%E5%AD%97)`.

**Comment by flibbles** [comment]
I'll look into this, but out of question. Does that actually make the link break? If I know markdown, it should still be clickable.

**Comment by flibbles** [comment]
This will be fixed as of v2.3.2 pushed today. It should also be less aggressive about escaping Unicode characters.

You can upgrade through your tiddlywiki's plugin handler.

**Comment by Darleey** [comment]
Hey, there~
I updated the plugin, but it doesn't work neither in the mode of single file or node.js server.

**Comment by flibbles** [comment]
What's happening? Is it not loading? Or not relinking? Or giving an error screen?

**Comment by Darleey** [comment]
The problem seems to keep as the same as before.

![image](https://user-images.githubusercontent.com/7878586/230816714-887e0d8c-32b9-4eeb-a52a-73216d2e1d15.png)

if I changed the title `Test-Source` to `Test-Source-1`

![image](https://user-images.githubusercontent.com/7878586/230816767-90eaad06-50c9-46c7-a55c-6198cd4154cc.png)

**Comment by flibbles** [comment]
Oh.

The TiddlyWiki team are apparently allowing `text/markdown` MIME type now too, instead of just `text/x-markdown`.

I'll fix.

**Comment by flibbles** [comment]
Try it now. Just pushed 2.3.3. It should work.

**Comment by Darleey** [comment]
It works well now, thanks 😊
