### ISSUE TITLE
BIDI TiddlyWiki and Relink

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#46]
I am using the solution here https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518632703
for using TW in real BIDI mode.

That means when you write a Right to Left Script, TW automatically switch the direction!

But when I install Relink, tiddler title inputbox does not follow direction! Uninstalling Relink the auto direction restored.

Does Relink use any css or any change to tiddler title? Thank you

**Comment by flibbles** [comment]
This is because Relink has to override the "title" edit template to include its warnings and "will update" notifications. This probably just means there's been a change to the original shadow tiddler and Relink has to update too. I'll fix it when I have a moment.

**Comment by kookma** [comment]
Thank you, no rush!

**Comment by flibbles** [comment]
Does this RTL functionality only exist in that PR you linked? Because if so, I'm not sure I should update Relink to support it until it's merged into master.

**Comment by kookma** [comment]
Yes, I assume https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518632703 and https://github.com/Jermolene/TiddlyWiki5/pull/7409 are the source of this issue.
By the way is there are hard coded `text direction` for title in edit mode? Is it possible to set the dir to auto?

**Comment by flibbles** [comment]
Hey Kookma,

I'm getting around to doing this, but I can't get rtl to work for anything. I put in arabic. I hit all combinations of ctrl-shift left. I'm honestly not sure how to do right-to-left.

Is it not in v5.2.7?

**Comment by kookma** [comment]
Hi @flibbles 
Well the latest version supporting BIDI can be found here: https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518553103

It is planned to be merged in 5.3.0 but now sure how things go!

On Windows to switch direction we use 


* <kbd>ctrl+left shift</kbd> changes direction to LTR
* <kbd>ctrl+right shift</kbd> changes direction to RTL

But to write arabic/persian/hebrew (I use Persian) you need to have installed language on your system! so I do not recommend to do so, may be you can copy paste from this old TW with BIDI support: http://kookma.rtl.tiddlyspot.com/

The issue with Relink comes from here https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518632703
We tried to change the hardcoded dir=ltr in TW, and it works, but then we faced with same issue if we install Relink.

You can leave this if you encounter problems until Jeremy merge the change into the core. The BIDI support now uses a separate branch.

**Comment by flibbles** [comment]
This _should_ be in now. Looked like a bunch of widgets in the EditTemplate/title tiddler needed a `dir` attribute, and they're there now. Obviously this has no effect until the next version is released, but once it does go live the latest Relink version shouldn't clobber this feature.

If you're using text direction on your own branch, Relink v2.3.4 should work for you.
