### ISSUE TITLE
Core macro `translink` missing from default whitelist

### ISSUE THREAD

**Issue by mateuszwilczek** [flibbles/tw5-relink#47]
It seems that the core macro `translink` is missing from the default whitelist. This macro wasn't documented until recently, it is now, and it has some upcoming improvements.

If I understand the code structure correctly, it would be a matter of adding line
`translink/title: title`
to /plugins/relink/tiddlers/macros.multids

**Comment by flibbles** [comment]
Sorry for the delay, but this is in now.

You were correct, it was as simple as adding a single line. I'm just unfathomably lazy sometimes.
