### ISSUE TITLE
[Idea] Add `target="_blank"` to links in the plugin info

### ISSUE THREAD

**Issue by mateuszwilczek** [flibbles/tw5-relink#49]
The links in plugin info tabs (readme, configuration, license) do not contain the `target="_blank"` attribute, and so they open the external site in the same browser tab.

This is quite surprising, since by default external links in TW open in a new tab.

**Comment by flibbles** [comment]
Yeah, I guess those things should open in a new tab. I'll sort that out soon.

**Comment by flibbles** [comment]
Resolved.
