### ISSUE TITLE
Use Backtranscludes indexer

### ISSUE THREAD

**Issue by linonetwo** [flibbles/tw5-relink#51]
From https://github.com/Jermolene/TiddlyWiki5/issues/847#issuecomment-778343681 seems you have a custom one?

As https://github.com/Jermolene/TiddlyWiki5/pull/6081 merged, maybe you can use the one in the core to save some maintainance.

**Comment by flibbles** [comment]
It's good that this is finally in. [I was pushing for transclude support for 8 years now](https://github.com/Jermolene/TiddlyWiki5/pull/2204). However, Relink supports version of TiddlyWiki back to 5.1.22. And it's mechanism is different. It doesn't look for hard transcludes so much as it looks for tiddlers used in reference to anything, including transcludes.

**Comment by linonetwo** [comment]
That was a long time, it seems it didn't get noticed by Jeremy.

So you are using a more comprehensive indexer, I think maybe you can try put it in the core too, so there can be, maybe "backreference[]" or something?

**Comment by flibbles** [comment]
My indexer is very Relink specific. It doesn't store just transcludes, but every kind of direct reference, and it takes all of the references and blurbs that Relink generates and tracks them.

What might be interesting would be a generic kind of indexer. There is one for links, and you've just added one for transclude. Their mechanisms must be similar, and are probably similar to my Relink indexer too. Maybe it could be made generic so we don't have so many copies of the indexers laying around.
