### ISSUE TITLE
[Idea] Export Tiddlers with n Levels Deep

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#53]
Relink is very powerful in determining all nodes of a tiddler under consideration.
Suppose an Export button with an option to select the number of levels, so:
- When export a tiddler, it uses the Relink to identify nodes (for example all tiddlers linked from the one under consideration)
- Then the current tiddler and its nodes will be exported
- If you use two levels deep, then the current tiddler and its nodes and the nodes of its nodes will be identified by Relink and will be exported.

For simplicity, one can consider only links and backlinks, or transcluded and linked tiddlers.

I thought to add this feature to Commander (Export Button), but first I need to have this in Relink or know how to do that with Relink.

**Comment by flibbles** [comment]
An export button of that sort would be a little outside the scope of Relink, but Relink provides the filter operators you'd need to make such an export button yourself. Here's a simple tiddler that would make a ViewTemplate button that exports the given tiddler and all tiddlers it references:
```
title: ExportTiddler
tags: $:/tags/ViewToolbar
caption: {{$:/core/images/export-button}} {{$:/language/Buttons/ExportTiddler/Caption}}
description: {{$:/language/Buttons/ExportTiddler/Hint}}

\define makeExportFilter()
[[$(currentTiddler)$]relink:references[]is[tiddler]!is[system]sort[title]] [[$(currentTiddler)$]] +[sort[title]]
\end

<$macrocall exportFilter=<<makeExportFilter>>lingoBase="exportReferences/"baseFilename={{!!title}}$name=exportButton/>
```

(This version requires `exportReferences/Hint` and `exportReferences/Caption` to exist so that button has the proper popup values, and you'd probably want to make its own icon, but it does work.)

**Comment by flibbles** [comment]
And here is the tiddler you need if you want to have a dymanic amount of depth:
```
bracket: ]
caption: {{$:/core/images/export-button}} {{ExportReferences/Caption}}
description: {{ExportReferences/Hint}}
operator: relink:references[]
tags: $:/tags/ViewToolbar
title: ExportReferences

\define makeExportFilter()
[range[0],[$(exportDepth)$]] :map:flat[range<currentTiddler>then{ExportReferences!!operator}else[]join[]addprefix{ExportReferences!!bracket}addprefix[[all[]addsuffix{ExportReferences!!bracket}join[]]
:map:flat[[$(currentTarget)$]subfilter<currentTiddler>]
+[is[tiddler]!is[system]unique[]sort[title]]
\end

\define exportReferencesButton(baseFilename lingoBase)
\whitespace trim
<$vars hint={{{ [<__lingoBase__>addsuffix[Hint]get[text]] }}} caption={{{  [<__lingoBase__>addsuffix[Caption]get[text]] }}}>
<span class="tc-popup-keep"><$button popup=<<qualify "$:/state/popup/export">> tooltip=<<hint>> aria-label=<<caption>> class=<<tv-config-toolbar-class>> selectedClass="tc-selected">
<$list filter="[<tv-config-toolbar-icons>match[yes]]">
{{$:/core/images/export-button}}
</$list>
<$list filter="[<tv-config-toolbar-text>match[yes]]">
<span class="tc-btn-text"><$text text=<<caption>>/></span>
</$list>
</$button></span></$vars><$reveal state=<<qualify "$:/state/popup/export">> type="popup" position="below" animate="yes">
<div class="tc-drop-down">
<$let count=2 currentTarget=<<currentTiddler>> >
<$list filter="[all[shadows+tiddlers]tag[$:/tags/Exporter]]">
<$list filter="[<currentTiddler>has[condition]subfilter{!!condition}limit[1]] ~[<currentTiddler>!has[condition]then[true]]" variable="ignore">
<$list variable=exportDepth filter="[range[3]]">
<$button class="tc-btn-invisible">
<$action-sendmessage $message="tm-download-file" $param=<<currentTiddler>> exportFilter=<<makeExportFilter>> filename={{{ [<__baseFilename__>addsuffix{!!extension}] }}}/>
<$action-deletetiddler $tiddler=<<qualify "$:/state/popup/export">>/>
<<exportDepth>> <$text text=' - ' /><$transclude field="description"/>
\end

<$macrocall $name=exportReferencesButton lingoBase="ExportReferences/" baseFilename={{!!title}} />
```
Holy fucking **shit** was this hard to make. Tiddlywiki does not like recursion in any sense.

Yes, this one does need those weird fields for this to work. You can't use extra `\define` to set variables and expect it to work.

**Comment by kookma** [comment]
This is wonderful! Much appreciated. I will add this to Commander with an acknowledgement note. If you mind you can add one of this as an example to Relink document wiki.

Thank you again for this wonderful plugin.

**Comment by flibbles** [comment]
Thanks. Not sure if what I made will work exactly for you. It's more just an example you can work with. It creates a dropdown with options for three tiers of depth X all the export types. It's not pretty. If it's in Commander, maybe it can have an edit field or something.

Just make damn sure that `makeExportFilter` does not depend on any other variables. The `tm-download-file` message does not import any context when it runs that filter. ...which made designing that filter an incredible pain.

**Comment by kookma** [comment]
> The `tm-download-file` message does not import any context when it runs that filter. ...which made designing that filter an incredible pain.
Yes, that's true.

Well yes, your code shows the functionality, I will take care of UI ;-)
Thank you!
