### ISSUE TITLE
Some tiddlers show up for every relink

### ISSUE THREAD

**Issue by yaisog** [flibbles/tw5-relink#54]
There are some tiddlers in my wiki that always show up in the list of tiddlers to be relinked. I have no idea why; it's only a small subset of my own system tiddlers.
With some debugging I traced it to the text matching operation, where the relink parser returns a parse tree of length 1 when it probably should be 0. I didn't get any further with my limited skills.

I made a Sharing Edition TW with one of these ominous tiddlers: [Link](https://tiddlywiki.com/prerelease/share##%5B%7B%22created%22%3A%2220240107101241270%22%2C%22text%22%3A%22%5C%5Cwhitespace%20trim%5Cn%5Cn%5C%5Cprocedure%20button-actions%28%29%5Cn%3C%24action-setfield%20%24tiddler%3D%5C%22%24%3A%2Ftemp%2FCompoundJournalTitle%5C%22%20text%3D%3C%3CcurrentTiddler%3E%3E%20%2F%3E%5Cn%3C%24action-navigate%20%24to%3D%5C%22Besprechungen%5C%22%20%2F%3E%5Cn%5C%5Cend%20button-actions%5Cn%5Cn%3C%25%20if%20%5B%3CcurrentTiddler%3Etag%5B%24%3A%2Ftags%2FCompoundJournal%5D%5D%20%5B%3CcurrentTiddler%3Etag%5B%24%3A%2Fmwi%2Ftags%2FBesprechungen%5D%5D%20%25%3E%5Cn%3C%24button%20class%3D%5C%22tc-btn-invisible%20mwi-btn-contextmenu%5C%22%20actions%3D%5C%22%3C%3Cbutton-actions%3E%3E%5C%22%3E%5Cn%5Ct%7B%7B%24%3A%2Fmwi%2Fimages-lucide%2Fsquare-pen%7D%7D%5Cn%5Ct%3Cspan%20class%3D%5C%22tc-btn-text%5C%22%3E%5Cn%5Ct%5CtBesprechung%20bearbeiten%5Cn%5Ct%3C%2Fspan%3E%5Cn%3C%2F%24button%3E%5Cn%3C%25%20endif%20%25%3E%22%2C%22modified%22%3A%2220241101074301488%22%2C%22tags%22%3A%22%22%2C%22title%22%3A%22%24%3A%2Fmwi%2Fobsolet%2Fui%2FButtons%2Fedit-compound%22%2C%22bag%22%3A%22default%22%2C%22type%22%3A%22text%2Fvnd.tiddlywiki%22%2C%22source%22%3A%22shared%22%2C%22revision%22%3A%221%22%7D%2C%7B%22title%22%3A%22%24%3A%2Fstate%2Fhttp-requests%22%2C%22text%22%3A%220%22%7D%2C%7B%22created%22%3A%2220241101083618417%22%2C%22title%22%3A%22%24%3A%2FStoryList%22%2C%22text%22%3A%22%22%2C%22list%22%3A%22%24%3A%2Fmwi%2Fobsolet%2Fui%2FButtons%2Fedit-compound%22%2C%22modified%22%3A%2220241101083618417%22%7D%5D)

If you drag the tiddler `$:/mwi/obsolet/ui/Buttons/edit-compound` from the sharing edition into e.g. https://flibbles.github.io/tw5-relink/ and then rename any tiddler in that wiki, you will see what I mean: it will show up for every renamed tiddler.

If you need more information I'll be happy to help.

Yaisog

**Comment by flibbles** [comment]
Yup. That's a bug. And it was an easy one to fix.

Problem should be fixed with release 2.4.4.

**Comment by yaisog** [comment]
I can confirm that 2.4.4 fixes the issue.
