### ISSUE TITLE
Doc Request

### ISSUE THREAD

**Issue by diego898** [flibbles/tw5-relink#7]
Hello,

Can you clarify the difference between the normal "References" tab and the "Relink References" tab? 

Thanks!

**Comment by flibbles** [comment]
Oh but in the meantime:

* References: Tiddlers that link to this one with <$link> or [[This syntax]]. This was already included in Tiddlywiki, and was used to tell you what tiddlers Tiddlywiki _couldn't_ relink for you.
* _Relink_ References: All Tiddlers that specify this one through links, macros, widgets, fields, etc... This is effectively a superior "References", but I wasn't sure if I should replace the old one. This list is all the tiddlers that'll update if you rename the given tiddler.

**Comment by flibbles** [comment]
"_Relink_ References tab" is now documented, and also includes a descriptive line above the listed tiddlers.
