### ISSUE TITLE
Add History Tiddler

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-relink#8]
I may recommend to add a history tiddler to show the date of latest change and what has been changed!

For example look at the Tiddler Commander plugin tiddler (readme, history, ...)

**Comment by flibbles** [comment]
Hmm. That would make the relinking start behaving differently than one would intuit after dropping the pluggin into their project.

Did you have a particular use-case which made you wish for this? Are you aware that Relink logs all its changes in the browser console?

**Comment by kookma** [comment]
Hi flibbles,
 I mean the plugin itself has a tiddler to show Change log
Whats new in  Relink 1.5.1
Whats new in Relin1.5
etc...

See this for example
https://kookma.github.io/TW-Commander/#%24%3A%2Fplugins%2Fkookma%2Fcommander%2Fhistory

**Comment by kookma** [comment]
> Are you aware that Relink logs all its changes in the browser console?

No!!
This is really great!
I am not sure if this mentioned in documentation or not!

Thank you

**Comment by flibbles** [comment]
Oh, a change log? Yeah. [right here](https://flibbles.github.io/tw5-relink/#Versions). It's been there.

**Comment by kookma** [comment]
Thanks!
